version: "3.8"
services:
  mongodb:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: latest
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTH: 2JnQBka8M7KFs59QqVfSopmbksD_4Nbakz4oigBUbVRgBUfVn
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    networks:
      - default
    depends_on:
      - mongodb
